version: "3.6"
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=sample
      - POSTGRES_DB=browser_calls
  app:
    stdin_open: true
    tty: true
    environment:
      - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - TWILIO_PHONE_NUMBER=+1XXXYYYZZZZ
      - TWILIO_APPLICATION_SID=APXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - API_KEY=SKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - API_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    build: .
    ports: 
      - "8080:8080"
    links:
      - db
