version: "3.6"
services:
  app:
    stdin_open: true
    tty: true
    environment:
      - DB_URL=jdbc:sqlite:/tmp/mydb.db
      - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - TWILIO_PHONE_NUMBER=+1XXXYYYZZZZ
      - TWILIO_APPLICATION_SID=APXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - API_KEY=SKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - API_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    build: .
    ports: 
      - "8080:8080"
